#!/bin/bash
#
# lib/cinder_backends/quantum
# Configure the QUANTUM backend

# Enable with:
#
#   CINDER_ENABLED_BACKENDS+=,quantum:quantumname

# Dependencies:
#
# - ``functions`` file
# - ``cinder`` configurations

# CINDER_CONF
# DATA_DIR
# VOLUME_GROUP_NAME

# clean_cinder_backend_quantum - called from clean_cinder()
# configure_cinder_backend_quantum - called from configure_cinder()
# init_cinder_backend_quantum - called from init_cinder()


# Save trace setting
_XTRACE_CINDER_QUANTUM=$(set +o | grep xtrace)
set +o xtrace


# TODO: resurrect backing device...need to know how to set values
#VOLUME_BACKING_DEVICE=${VOLUME_BACKING_DEVICE:-}

# Entry Points
# ------------

# cleanup_cinder_backend_quantum - Delete volume group and remove backing file
# cleanup_cinder_backend_quantum $be_name
function cleanup_cinder_backend_quantum {
    local be_name=$1

    # Campsite rule: leave behind a volume group at least as clean as we found it
    clean_quantum_volume_group $VOLUME_GROUP_NAME-$be_name
    clean_quantum_filter
}

# configure_cinder_backend_quantum - Set config files, create data dirs, etc
# configure_cinder_backend_quantum $be_name
function configure_cinder_backend_quantum {
    local be_name=$1

    iniset $CINDER_CONF $be_name volume_backend_name $be_name
    iniset $CINDER_CONF $be_name volume_driver "cinder.volume.drivers.quantum.QUANTUMVolumeDriver"
    iniset $CINDER_CONF $be_name volume_group $VOLUME_GROUP_NAME-$be_name
    iniset $CINDER_CONF $be_name target_helper "$CINDER_ISCSI_HELPER"
    iniset $CINDER_CONF $be_name quantum_type "$CINDER_QUANTUM_TYPE"
    iniset $CINDER_CONF $be_name volume_clear "$CINDER_VOLUME_CLEAR"
}

# init_cinder_backend_quantum - Initialize volume group
# init_cinder_backend_quantum $be_name
function init_cinder_backend_quantum {
    local be_name=$1

    # Start with a clean volume group
    init_quantum_volume_group $VOLUME_GROUP_NAME-$be_name $VOLUME_BACKING_FILE_SIZE
}

# Restore xtrace
$_XTRACE_CINDER_QUANTUM

# mode: shell-script
# End:
