# This compose file will run the VS Managment API (REST server) and VS Management UI (standalone) servers. 
# To run just the API you can comment out the vs-mgmt-ui service. However the API is required to run the UI. 
# The images are housed in the gitlab/cypress registry (images.corp.pivot3.com). Follow the instructions 
# here if you have never logged in to the registry 
# before: https://cypress.corp.pivot3.com/build/P3DockerUtils/-/tree/master

version: "3"
services:
  vs-mgmt-api:
    image: images.corp.pivot3.com/dev/ui/quantum-vs-mgmt/vs-mgmt-api
    
    # optionally mount the REST Server logs to a local directory
    # volumes:            
    #   - "/tmp/vsmslogs:/vsms/java/jars/null/Pivot3/VSMS"

    ports:
      # API port (https://<host>:8080/p3api/v2)
      - "8080:8080"

    environment:
      # API username (vPG username). Default 'quantum'.
      USERNAME: pivot3

      # API password (vPG username) Default 'quantum'.
      PASSWORD: pivot3

      # optional comma separated list of IPs to discover when the server boots
      #AUTO_DISCOVERY_IP: 10.134.6.22
      AUTO_DISCOVERY_IP: 10.134.6.222,10.134.6.232,10.134.6.242

      # optional comma separated list of IPs to filter. Only nodes with at least one
      # IP in this list will show up in the domain.
      #IP_ADDRESS_FILTER: 10.134.6.22
      IP_ADDRESS_FILTER: 10.134.6.222;10.134.6.232;10.134.6.242

  vs-mgmt-ui:
    image: images.corp.pivot3.com/dev/ui/quantum-vs-mgmt/vs-mgmt-standalone
    depends_on:
      - "vs-mgmt-api"
    ports:
      # IP to access the web app (https://<host>:8444/p3plugin/p3-app/index.html)
      - "8443:8443"

      # websocket port from the browser to the webapp
      - "8887:8887"
    environment:
      # API username (vPG username)
      API_USERNAME: tpsadmin

      # API password (vPG password)
      API_PASSWORD: pivot3

      # contact IP or hostname (service name) of the API service
      API_SERVICE_NAME: vs-mgmt-api
